kafka:
  abstraction:
    bootstrap-servers: localhost:9092
    
    security:
      enabled: false
      protocol: SSL
      keystore-location: /path/to/keystore.jks
      keystore-password: changeit
      keystore-type: JKS
      truststore-location: /path/to/truststore.jks
      truststore-password: changeit
      truststore-type: JKS
      key-password: changeit
      ssl-endpoint-identification-algorithm: ""
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      compression-type: snappy
      max-in-flight-requests-per-connection: 5
      enable-idempotence: true
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
    
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: default-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval-ms: 5000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 3000
      max-poll-records: 500
      max-poll-interval-ms: 300000
      fetch-min-bytes: 1
      fetch-max-wait-ms: 500
    
    example:
      enabled: false

logging:
  level:
    com.example.kafka.abstraction: DEBUG
    org.apache.camel: INFO
    org.apache.kafka: INFO